#!/sbin/bb/busybox sh

# $1 - "msm_thermal"
# $2 - value=
# Created By Dorimanx

BB=/sbin/bb/busybox

# get values from profile
PROFILE=$($BB cat /data/.b--b/.active.profile);
. /data/.b--b/"$PROFILE".profile;

$BB echo "Y" > /sys/module/msm_thermal/parameters/intelli_enabled;
$BB echo "$limit_temp_degC" > /sys/module/msm_thermal/parameters/limit_temp_degC;
$BB echo "$core_limit_temp_degC" > /sys/module/msm_thermal/parameters/core_limit_temp_degC;
/system/bin/stop thermal-engine;
/system/bin/stop thermal-engine;
/system/bin/stop thermal-engine;

$BB echo ${msm_thermal};
