#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox
if [ "$($BB mount | $BB grep "on /system" | $BB cut -c 69-70 | $BB grep -c ro)" -eq "1" ]; then
        $BB mount -o remount,rw /system;
fi;

$BB cp -a /res/misc/clean_hosts/hosts /system/etc/hosts;
$BB chmod 622 /system/etc/hosts;
$BB echo "AD Blocker: REMOVED";
$BB mount -o remount,ro /system;
